scalar Date

type MyType {
   created: Date
}

type Item {
  id: Int
  date: Date
  category: String
  title: String
  value: Float
}

input ItemInput {
  date: String
  category: String
  title: String
  value: Float
}

input FilterInput {
  id: Int
}

type Query {
  items: [Item]
}

type Mutation {
  addItem(data: ItemInput): Item
  updateItem(id: Int!, data: ItemInput): Item
  dropItem(filter: FilterInput): Boolean
}
