scalar Date

type MyType {
   created: Date
}

type Item {
  id: Int
  date: Date
  category: String
  title: String
  value: Float
}

input ItemInput {
  date: String
  category: String
  title: String
  value: Float
}

input FiltroInput {
  id: Int
}

type Query {
  items: [Item]
}

type Mutation {
  criarItem(data: ItemInput): Item
  atualizarItem(id: Int!, data: ItemInput): Item
  deletarItem(filtro: FiltroInput): Boolean
}
